language: node_js
node_js: 12
matrix:
  include:
  - name: "Polyfill tests"
    script:
    - npm run codecov
  - name: "test262 tests"
    script:
    - npm run test262
  - name: "Specification compilation"
    script:
    - npm run build
    deploy:
      local_dir: out/
      target_branch: gh-pages
      keep_history: true
      provider: pages
      skip_cleanup: true
      github_token: $GH_ACCESS_TOKEN
      committer_from_gh: true
      on:
        branch: main
